//===================================================================================
// Microsoft patterns & practices
// Composite Application Guidance for Windows Presentation Foundation and Silverlight
//===================================================================================
// Copyright (c) Microsoft Corporation.  All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE.
//===================================================================================
// The example companies, organizations, products, domain names,
// e-mail addresses, logos, people, places, and events depicted
// herein are fictitious.  No association with any real company,
// organization, product, domain name, email address, logo, person,
// places, or events is intended or should be inferred.
//===================================================================================
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.ProjectLinker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.ProjectLinker.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create Project Linker output window..
        /// </summary>
        internal static string FailedToCreateOutputWindow {
            get {
                return ResourceManager.GetString("FailedToCreateOutputWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; already exists in the file system. No link was created in target project &apos;{1}&apos;..
        /// </summary>
        internal static string FileAlreadyExistsInFileSystem {
            get {
                return ResourceManager.GetString("FileAlreadyExistsInFileSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The linked file &apos;{0}&apos; was removed from target project &apos;{1}&apos;..
        /// </summary>
        internal static string FileLinkSuccessfullyRemoved {
            get {
                return ResourceManager.GetString("FileLinkSuccessfullyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The linked file &apos;{0}&apos; was added to target project &apos;{1}&apos;..
        /// </summary>
        internal static string FileSuccessfullyLinked {
            get {
                return ResourceManager.GetString("FileSuccessfullyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; is not linked from project &apos;{1}&apos;. No action taken..
        /// </summary>
        internal static string FileToRemoveDoesNotExistInTarget {
            get {
                return ResourceManager.GetString("FileToRemoveDoesNotExistInTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder &apos;{0}&apos; was created in target project &apos;{1}&apos;..
        /// </summary>
        internal static string FolderCreatedInTarget {
            get {
                return ResourceManager.GetString("FolderCreatedInTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder &apos;{0}&apos; was removed from target project &apos;{1}&apos;..
        /// </summary>
        internal static string FolderSuccessfullyRemoved {
            get {
                return ResourceManager.GetString("FolderSuccessfullyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder &apos;{0}&apos; in target project &apos;{1}&apos; is not empty, hence it was not removed..
        /// </summary>
        internal static string FolderToRemoveIsNotEmpty {
            get {
                return ResourceManager.GetString("FolderToRemoveIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder &apos;{0}&apos; already exists in the file system. This folder was included in target project &apos;{1}&apos;..
        /// </summary>
        internal static string IncludingExistingFolderInProject {
            get {
                return ResourceManager.GetString("IncludingExistingFolderInProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Project Tracker..
        /// </summary>
        internal static string InitializingProjectTracker {
            get {
                return ResourceManager.GetString("InitializingProjectTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item &apos;{0}&apos; was not linked because it is excluded by the current filters in target project &apos;{1}&apos;..
        /// </summary>
        internal static string ItemExcludedByFilter {
            get {
                return ResourceManager.GetString("ItemExcludedByFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Linker.
        /// </summary>
        internal static string LoggerOutputPaneTitle {
            get {
                return ResourceManager.GetString("LoggerOutputPaneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects are already linked..
        /// </summary>
        internal static string ProjectFilesAlreadyLinked {
            get {
                return ResourceManager.GetString("ProjectFilesAlreadyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Linker.
        /// </summary>
        internal static string ProjectLinkerCaption {
            get {
                return ResourceManager.GetString("ProjectLinkerCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectLinker:  {0}.
        /// </summary>
        internal static string ProjectLinkerErrorWithPrefix {
            get {
                return ResourceManager.GetString("ProjectLinkerErrorWithPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects successfully linked..
        /// </summary>
        internal static string ProjectsSuccessfullyLinked {
            get {
                return ResourceManager.GetString("ProjectsSuccessfullyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link between target project &apos;{0}&apos;  and source project &apos;{1}&apos; was successfully restored..
        /// </summary>
        internal static string ProjectsSuccessfullyRelinked {
            get {
                return ResourceManager.GetString("ProjectsSuccessfullyRelinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target project &apos;{0}&apos; was successfully unlinked from source project &apos;{1}&apos;..
        /// </summary>
        internal static string ProjectsSuccessfullyUnlinked {
            get {
                return ResourceManager.GetString("ProjectsSuccessfullyUnlinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target project &apos;{0}&apos; temporarily unlinked from source project &apos;{1}&apos; on Source project closure..
        /// </summary>
        internal static string ProjectsUnlinkedOnSourceClose {
            get {
                return ResourceManager.GetString("ProjectsUnlinkedOnSourceClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target project &apos;{0}&apos; temporarily unlinked from source project &apos;{1}&apos; on Target project closure..
        /// </summary>
        internal static string ProjectsUnlinkedOnTargetClose {
            get {
                return ResourceManager.GetString("ProjectsUnlinkedOnTargetClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project &apos;{1}&apos; is already linked to source project &apos;{2}&apos; as a Target. Link between target project &apos;{0}&apos; and source project &apos;{1}&apos; was not restored..
        /// </summary>
        internal static string SourceProjectIsAlreadyLinkedAsTarget {
            get {
                return ResourceManager.GetString("SourceProjectIsAlreadyLinkedAsTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project &apos;{0}&apos; is already linked to target project {2} as a Source. Link between target project &apos;{0}&apos; and source project &apos;{1}&apos; was not restored..
        /// </summary>
        internal static string TargetProjectIsAlreadyLinkedAsSource {
            get {
                return ResourceManager.GetString("TargetProjectIsAlreadyLinkedAsSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project &apos;{0}&apos; is already linked to source project &apos;{2}&apos; as a Target. Link between target project &apos;{0}&apos; and source project &apos;{1}&apos; was not restored..
        /// </summary>
        internal static string TargetProjectIsAlreadyLinkedAsTarget {
            get {
                return ResourceManager.GetString("TargetProjectIsAlreadyLinkedAsTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target project &apos;{0}&apos; is waiting for source project with GUID {1} to be loaded in order to restore its link..
        /// </summary>
        internal static string TargetProjectWaitingForSource {
            get {
                return ResourceManager.GetString("TargetProjectWaitingForSource", resourceCulture);
            }
        }
    }
}
